name: "Get Rounded Time"
author: "Gerred Dillon <hello@gerred.org>, Shahar Frank <srfrnk@gmail.com>, Joshua Chan <josStorer@outlook.com>, Nitin Khanna <mail@nitinkhanna.com>"
description: "Get the current time rounded to the closest interval with `format`, `utcOffset`, `interval` info"
branding:
  icon: clock
  color: blue
inputs:
  format:
    description: "Time format to use using [MomemtJS format syntax](https://momentjs.com/docs/#/displaying/format/)"
    required: false
  utcOffset:
    description: "UTC offset to use using [MomemtJS utcOffset syntax](https://momentjs.com/docs/#/manipulating/utc-offset/)"
    required: false
  interval:
    description: "Interval by which to round off the time - 5, 10, 15, 30 etc"
    required: false
  intervalType:
    description: "Type of Interval - minutes, hours, seconds - Refer to moment.duration docs for all available formats."
    required: false
  method:
    description: "Rounding method, floor, ceil (It supports all the round methods available in NodeJS Math package)"
    required: false
outputs:
  time:
    description: "The ISO time this action was run, **not** affected by the parameter `utcOffset`  e.g. '2020-01-01T00:30:15.000Z'"
  ISOTime:
    description: "Same as `time`"
  readableTime:
    description: "Human-friendly time - affected by the parameter `utcOffset`  e.g. 'Wed Jan 01 2020 08:30:15 GMT+0800'"
  formattedTime:
    description: "The time this action was run - formatted using `format` and `utcOffset` inputs"
  year,month,day,hour,minute,second,millisecond:
    description: "Digital outputs, just as names"
runs:
  using: "node12"
  main: "dist/index.js"
